---
title: "R Notebook"
output: html_notebook
---


```{r}
library(sf)
library(tidyverse)
```

```{r}
burglaries <- read.csv("../data/burglaries_2023.csv")
census <- read.csv("../data/census.csv")
tracts <- read_sf("../data/DC")
```

```{r}
tracts |> 
  ggplot() +
  geom_sf()
```

```{r}
tracts |> 
  ggplot() +
  geom_sf() +
  geom_point(
    data = burglaries |> drop_na(latitude),
    aes(x = longitude, y = latitude),
    size = 0.1
    )
```

```{r}
burglaries_geo <- st_as_sf(
  burglaries |> drop_na(latitude, longitude), 
  coords = c('longitude', 'latitude'),
  crs = st_crs(tracts)
)
```

```{r}
tracts |> 
  ggplot() +
  geom_sf() +
  geom_sf(data = burglaries_geo, size= 0.1)
```

```{r}
burglaries_zips <- st_join(burglaries_geo, tracts, join=st_within, left = FALSE)
#burglaries_zips
  
```

```{r}
burglaries_zips |> 
  st_drop_geometry() |> 
  group_by(NAME) |> 
  count(name = "num_burglaries") |> 
  arrange(desc(num_burglaries))
```

```{r}
name = 160

tracts |> 
  filter(NAME == name) |> 
  ggplot() +
  geom_sf() +
  geom_sf(data = burglaries_zips |> filter(NAME == name),
          aes(color = weapon_description))
```

```{r}
tracts |> 
  ggplot() +
  geom_sf() +
  geom_sf(data = burglaries_zips,
          aes(color = weapon_description))
```

```{r}
burglaries_zips <- burglaries_zips |> 
  mutate(TRACTCE = as.numeric(str_sub(TRACTCE, 2, -1)))
burg_zips_census <- left_join(census, burglaries_zips, by = c("tract" = "TRACTCE"))
```

```{r}
# Exploratory Analysis
ndf <- burg_zips_census |> 
  drop_na(incident_number)|> 
  filter(population>0)
ndf <- ndf |> 
  group_by(tract) |>
  mutate(incident_number = as.character(incident_number)) |> 
  summarize(incident_sum = n(), population=mean(population), 
            per_cap = 1000 * incident_sum/population,
            median_income = mean(median_income))|> 
  arrange(desc(per_cap))
ndf
```

```{r}
pr_burg_income <- glm('incident_sum ~ median_income',
 data = ndf,
 family = "poisson")
```

```{r}
summary(pr_burg_income)
```

```{r}
median_tract_income = 50000
exp(3.143 - .00001932*median_tract_income)
```

